apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: crio-image-lister
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: crio-image-lister
  template:
    metadata:
      labels:
        app: crio-image-lister
    spec:
      hostPID: true
      hostNetwork: true
      restartPolicy: Always  # Must be "Always" for DaemonSet
      containers:
      - name: lister
        image: alpine:3.18
        securityContext:
          privileged: true
        command:
          - /bin/sh
          - -c
          - |
            echo "Installing crictl..."
            wget -qO- https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.31.0/crictl-v1.31.0-linux-amd64.tar.gz | tar -xz -C /usr/local/bin
            echo "runtime-endpoint: unix:///var/run/crio/crio.sock" > /etc/crictl.yaml
            echo "Listing cached CRI-O images:"
            crictl images
            echo "Sleeping to prevent container restart..."
            sleep 3600
        volumeMounts:
        - name: var-run
          mountPath: /var/run
        - name: etc-crio
          mountPath: /etc/crio
      volumes:
      - name: var-run
        hostPath:
          path: /var/run
      - name: etc-crio
        hostPath:
          path: /etc/crio
