apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: crio-image-cleaner
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: crio-image-cleaner
  template:
    metadata:
      labels:
        app: crio-image-cleaner
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: cleaner
        image: docker.io/alpine:3.18
        securityContext:
          privileged: true
        command:
          - /bin/sh
          - -c
          - |
            echo "Deleting all CRI-O images..."
            crictl images -q | xargs -r -n 1 crictl rmi
            echo "Done. Sleeping to keep pod alive for observation."
            sleep 3600
        volumeMounts:
        - name: var-run
          mountPath: /var/run
        - name: etc-crio
          mountPath: /etc/crio
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
      volumes:
      - name: var-run
        hostPath:
          path: /var/run
      - name: etc-crio
        hostPath:
          path: /etc/crio
