apiVersion: rtf.mulesoft.com/v1
kind: HTTPRouteTemplate
metadata:
  name: example-template-ingress
  namespace: rtf
spec:
  baseEndpoints:
  - "mulepoc.wataniya.com.sa"
  resources:
  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: {{ .ResourceName }}
      namespace: {{ .Namespace }}
    spec:
      parentRefs:
      - name: {{ .GatewayName }}
      hostnames:
      - {{ .Host }}
      rules:
      - matches:
        - path:
            type: PathPrefix
            value: {{ .Path }}
        filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
        backendRefs:
        - name: {{ .Service.Name }}
          port: {{ .Service.Port }}